### ISSUE TITLE
Instance creation in WGPUCore fails if GLFW is loaded first on Linux Machine

### ISSUE THREAD

**Issue by arhik** [JuliaWGPU/WGPUgfx.jl#12]
This is minimal code where GLFW is causing issue on Linux Machine ...

```julia
# Working code
using WGPUNative

instanceDescriptor = cStruct(WGPUInstanceDescriptor)
instanceDescriptor.nextInChain = C_NULL
wgpuCreateInstance(instanceDescriptor |> ptr)

``` 
If we try the same code with GLFW loaded first on Linux Machine x86_64, it crashes with rust unwrap error in wgpu-native library. (you can reproduce this on a fresh repl)

```julia
# Not working as GLFW is loaded first
using GLFW
using WGPUNative

instanceDescriptor = cStruct(WGPUInstanceDescriptor)
instanceDescriptor.nextInChain = C_NULL
wgpuCreateInstance(instanceDescriptor |> ptr)

#  This does not work if GLFW is loaded first

```

This shouldn't happen since they are independent libraries. If anyone has any clue about what could be possibly happening, I would appreciate it.

**Comment by arhik** [comment]
The issue #11 is most likely happening because of this. I would appreciate if anyone verifies this.

**Comment by VarLad** [comment]
@arhik I can confirm the error with this as well. 
Will try on Windows when I get my hands on a Windows machine.

**Comment by VarLad** [comment]
@arhik I can further narrow it down to 
```julia
using GLFW_jll
ccall((:glfwInit, libglfw), Cint, ())

using WGPUNative
instanceDescriptor = cStruct(WGPUInstanceDescriptor)
instanceDescriptor.nextInChain = C_NULL
wgpuCreateInstance(instanceDescriptor |> ptr)
```

**Comment by VarLad** [comment]
@arhik Would it be possible for you to create a C equivalent of what I provided, if its trivial? 
That would help when asking the wgpu community/experts about this.

**Comment by uncomfyhalomacro** [comment]
Here is the log with `RUST_BACKTRACE=full`
[wgpu-julia-log.txt](https://github.com/JuliaWGPU/WGPUgfx.jl/files/12928235/wgpu-julia-log.txt)

**Comment by VarLad** [comment]
@arhik Another idea. Can you think of a minimal example involving one of the JuliaWGPU libraries and system's GLFW (directly) via ccalls?
That would be good to check if the issue is from BinaryBuilder's GLFW or GLFW in Linux itself

**Comment by arhik** [comment]
> @arhik Would it be possible for you to create a C equivalent of what I provided, if its trivial? That would help when asking the wgpu community/experts about this.

@uncomfyhalomacro shared a log file that matches my issue topic. It suggests that the toplevel call is wgpuCreateInstance (which is a ccall already). So I don't see it helping. It is Julia issue definitely and is platform specific issue so wgpu guys can't help. That leaves us with BinaryBuilder's option you were alluding to. I will try that first. I will leave inspection using `ccall` as last option if there is anything we can do.

**Comment by VarLad** [comment]
@arhik That makes sense. I would just like to add that, using binaries from my system:
```julia
ccall((:glfwInit, :libglfw), Cint, ())

using WGPUNative
instanceDescriptor = cStruct(WGPUInstanceDescriptor)
instanceDescriptor.nextInChain = C_NULL
wgpuCreateInstance(instanceDescriptor |> ptr)
```
This works. I'm wondering if its a packaging issue from BinaryBuilder side. 
Would be nice if you could think of a minimal example using glfw (using ccall) and WGPUNative.

**Comment by arhik** [comment]
Cool. From my end: Linux version used to work on older version wgpu-native. Infact I started with Linux. So i am trying to use older wgpu-native and newer GLFW library. See if I can narrow it.

**Comment by VarLad** [comment]
@arhik I've further narrowed it down to (this works):
(In your environment folder, where your Project.toml file is, create another file called LocalPreferences.toml, its contents being:

```toml
[Libglvnd_jll]
libEGL_path = "/usr/lib64/libEGL.so.1"
```
)
This forces GLFW_jll (and GLFW.jl) to use system libEGL instead of BinaryBuilder one.

Now this code works:
```julia
using GLFW
using WGPUNative

instanceDescriptor = cStruct(WGPUInstanceDescriptor)
instanceDescriptor.nextInChain = C_NULL
wgpuCreateInstance(instanceDescriptor |> ptr)
```

**Comment by VarLad** [comment]
@arhik I'll try seeing if I can get the BinaryBuilder version of Libglvnd_jll updated to the latest version.
In the meanwhile, can you somehow try out if any example works for you using the above workaround? I'll be a bit busy for 2 days or so....

**Comment by arhik** [comment]
> @arhik I've further narrowed it down to (this works): (In your environment folder, where your Project.toml file is, create another file called LocalPreferences.toml, its contents being:
> 
> ```toml
> [Libglvnd_jll]
> libEGL_path = "/usr/lib64/libEGL.so.1"
> ```
> 
> ) This forces GLFW_jll (and GLFW.jl) to use system libEGL instead of BinaryBuilder one.
> 
> Now this code works:
> 
> ```julia
> using GLFW
> using WGPUNative
> 
> instanceDescriptor = cStruct(WGPUInstanceDescriptor)
> instanceDescriptor.nextInChain = C_NULL
> wgpuCreateInstance(instanceDescriptor |> ptr)
> ```
> 
> Make sure that
> 
> * LocalPreferences.toml file is in your environment folder
> * `/usr/lib64/libEGL.so.1` exists. If its by another name, find it. If it doesn't exist at all, make sure to install it first.

Super. I was suspicious of Libglvnd yesterday, but fell asleep. I should have mentioned to you. It would have saved your time.  

We might have to package EGL for Linux. Usually we can't expect users to have this library. Updating Libglvnd_jll will be right thing to do. If its not happening for some reason we will have to create artifact.

**Comment by arhik** [comment]
At line https://github.com/JuliaWGPU/WGPUCore.jl/blob/main/src/linuxglfw.jl#L83C43-L83C43 replace `instance` with `instance[]`.

**Comment by arhik** [comment]
updating Libglvnd_jll to 1.7.0 didn't help. If anyone can confirm it would be great. (You can find the repository here https://github.com/arhik/Libglvnd_jll.jl.git)

**Comment by arhik** [comment]
For now workaround like @VarLad suggested works. I confirm that. Library path for EGL will be different for different linux systems. We will have to find a way to do it using Libdl.

**Comment by VarLad** [comment]
@arhik Apologies for the delayed reply and thank you for the continued effort :sweat: 
Can you try adding a build dependency called Xorg_glproto_jll to the build_tarballs.jl file?

**Comment by arhik** [comment]
Adding Xorg_gl_proto_jll didn't do anything. Artifacts.toml is exactly the same. Hashes would have changed if content of library build files changed.

**Comment by asterycs** [comment]
Hello! :wave:

I was checking out WGPUNative for my project and ran in to (what seems to be) this exact issue. I'm on Manjaro Linux and `eglinfo` reports
```
...
EGL API version: 1.5
EGL vendor string: NVIDIA
EGL version string: 1.5
...
```
@VarLad which exact platform are you on? Your suggested workaround doesn't seem to work for me unfortunately. It seems to me that either my local `libegl` is broken in the same way or my `LocalPreferences.toml` isn't read the way I expect.

**Comment by arhik** [comment]
You can try directly replacing libEGL.so artifact that Julia uses (but make sure to make a copy of the originals to revert it later)

To find the path of `libEGL` path try the following statements in Julia REPL.

> julia> using Libglvnd_jll
> 
> julia> libEGL
> "/home/arhik/.julia/artifacts/37dda4e57d9de95c99d1f8c6b3d8f4eca88c39a2/lib/libEGL.so"
> 

find system level `libEGL` path and copy it to your artifact folder. If this works, then your system level `libEGL` is fine.

**Comment by asterycs** [comment]
Thanks for the help! I replaced the `libEGL.so` with the one from my system and this made the [minimal example](https://github.com/JuliaWGPU/WGPUgfx.jl/issues/12#issuecomment-1767489773) work.

 I could also verify that changing the path to `libEGL` using `LocalPreferences.toml` had the desired effect on the library path:
```
julia> libEGL
"/usr/lib64/libEGL.so.1"
```
After deleting my `~/.julia/` also this option seems to work for me (I must have done something unexpected the first time). 

I can thus confirm that the BinaryBuilder `libEGL` appears to have an issue.

**Comment by asterycs** [comment]
For what it's worth, a custom built [libglvnd v1.7.0](https://github.com/JuliaWGPU/WGPUgfx.jl/issues/12#issuecomment-1778699860) also didn't make a difference for me.

The [system libglvnd](https://gitlab.archlinux.org/archlinux/packaging/packages/libglvnd/-/blob/main/PKGBUILD?ref_type=heads) that I'm using seems to have some additional build flags that are missing in the [BinaryBuilder version](https://github.com/JuliaPackaging/Yggdrasil/blob/master/L/Libglvnd/build_tarballs.jl). I'll investigate whether they would solve the problem.

**Comment by arhik** [comment]
@asterycs Thank you for verifying.

**Comment by arhik** [comment]
Linux was working with `Libglvnd_jll` (v1.3) and `wgpu-native` versions (0.12, 0.14).

Since then there is change in `Libglvnd_jll` version to v1.6 and we upgraded `wgpu-native` binary artifacts to v0.16.

Since previous `Libglvnd_jll` library v1.3 was working for us with wgpu-native version v0.14 and there is no change in build flags, I am clueless.

Yesterday I had to separate `GLFW` code from `WGPUCore`. This decoupling will allow us to try different window libraries. Also we need headless rendering for plots like in `Makie`. You can find code for GUI here https://github.com/JuliaWGPU/WGPUGUI

**Comment by arhik** [comment]
A possible fix here #16. Let me know if this good enough. You will have to install `WGPUGUI` library using link. (It is not registered yet). And updated code of `WGPUgfx`.

**Comment by asterycs** [comment]
Thanks for setting this up @arhik . Looks like a reasonable solution to me!

**Comment by arhik** [comment]
We were having discussion on our approach in [slack](https://julialang.slack.com/archives/C6M4DQA5P/p1700070159366089). There is some disagreement in our approach. Lets see we can come to alternative solution.
