### ISSUE TITLE
Use LocalPreferences.toml to use system level libEGL by default for linux systems

### ISSUE THREAD

**Issue by arhik** [JuliaWGPU/WGPUgfx.jl#16]

**Comment by arhik** [comment]
@VarLad came up with this option. Now we have to figure out how to ship this solution that works on all Linux-systems.

**Comment by arhik** [comment]
`Preferences.jl` looks interesting.

**Comment by arhik** [comment]
[slack](https://julialang.slack.com/archives/C6M4DQA5P/p1700070159366089) discussion is going on this approach.

**Comment by arhik** [comment]
WGPUCanvas.jl is registered with this fix https://github.com/JuliaRegistries/General/pull/95352

**Comment by arhik** [comment]
We can close this once anyone confirms that this is indeed fixed.

**Comment by VarLad** [comment]
@arhik Apologies, I'm running into the same issue again (it crashes with GLFW loaded)
I believe that the examples need to be updated to use `WGPUCanvas.jl` instead of directly `GLFW.jl`?

**Comment by VarLad** [comment]
I was able to get the cube example running (using the hack I wrote). 
I'm guessing that the examples have to be updated to use WGPUCanvas.jl instead of GLFW.jl? 
@arhik Correct me if I'm wrong of this

**Comment by arhik** [comment]
May be you are not placing `LocalPreferences.toml` file in global folder. I am placing it in the julia dev folder (like ~/.julia/dev). Yes. On linux I had to manually create `LocalPreferences.toml` file like you suggested and it works but I wish it can automated. I will have to dig into it. Anyways check know your configuration and let me know.

**Comment by arhik** [comment]
By the way all examples in the GUI must be flipped vertically if you are using the master branch; I made few changes while working on gaussian splatting code.

**Comment by VarLad** [comment]
@arhik The LocalPreferences.jl file worked but I'm asking if instead of directly using GLFW.jl, does it make more sense to use WGPUCanvas instead? 
Seems like its function is to reduce boilerplate of working with WGPU + GLFW :P

**Comment by arhik** [comment]
Yes totally. A little more abstraction with `WGPUCanvas` will help. If we don't have to use these in examples like these 

> using GLFW
> using GLFW: WindowShouldClose, PollEvents, DestroyWindow 

with abstracted functions defined in `WGPUCanvas` would be great.

**Comment by arhik** [comment]
I am not happy with too much clutter of duplicate includes too. I see your point.

**Comment by VarLad** [comment]
@arhik Is there any examples of WGPUCanvas.jl in action?

**Comment by arhik** [comment]
All examples use `WGPUCanvas`.  `WGPUgfx` loads `WGPUCanvas`. And its `WGPUCanvas`'s job to load appropriate surface based on platform.

**Comment by arhik** [comment]
If I misunderstood your question correct me please.

**Comment by arhik** [comment]
It doesn't look like it but in `WGPUCanvas` we provide `getCanvas` through `WGPUCore` definitions.
https://github.com/JuliaWGPU/WGPUgfx.jl/blob/f95dfd5114765abd251e2c452fbc49dffbf0c474/src/scene.jl#L22

**Comment by arhik** [comment]
Platform dependent canvas will be loaded here. 

https://github.com/JuliaWGPU/WGPUCanvas.jl/blob/02d0b98a0cef3cefd755d9fa4a30bb3e258ee06b/src/WGPUCanvas.jl#L35

**Comment by VarLad** [comment]
@arhik Ah, sorry, I thought WGPUCanvas acted as a replacement for directly using GLFW :sweat_smile: 
Didn't see that it was imported and used by WGPUgfx

By the way, were you able to figure out why the libglvnd provided by BinaryBuilder gives issues here?

**Comment by arhik** [comment]
No. But its a prevalent Symbol collision issue.

**Comment by VarLad** [comment]
@arhik I'm interested in helping to get the circle example working.
I guess I need to work on the circle primitive first. I believe that would be a good starting point for contribution as well.

Can you give me some directions towards this?

**Comment by arhik** [comment]
UI circle example should help. Divide circle into triangle primitive. Within triangle primitive, you only need two sides for as a template unit (i.e three vertices). You will have rotate these three vertices with 360/n degrees ( n - no of divisions). All these already part of ui/circle.jl. 

https://github.com/JuliaWGPU/WGPUgfx.jl/blob/main/src/ui/circle.jl

**Comment by arhik** [comment]
Basically you should return a Circle object with indexData, vertexData, colorData and normalData (optional)

**Comment by VarLad** [comment]
@arhik Is there any example that deals with 2D shapes?

**Comment by arhik** [comment]
plane.jl is simplest

**Comment by VarLad** [comment]
@arhik Thanks, that was really helpful. 
Do you have an example which shows working with mouse or keypresses?

**Comment by arhik** [comment]
splat.jl should be listening to both mouse events and keypresses. No visual aid for key pressess. That would interesting project.

For splat.jl to work you will have to download a file from here https://drive.google.com/drive/folders/1B8fBd3ivh1OuJBY_P28woJfmzvWc8WlO

**Comment by VarLad** [comment]
@arhik I looked at the specific example (splat.jl) but I can't seem to find the specific lines that seem to be listening to keypresses or mouse movements.
Is there a way to print them to screen?

**Comment by arhik** [comment]
key - 'a' for attaching event system and 'd' for detaching event system. You should see mouse pointer output and key events in the terminal window.

**Comment by arhik** [comment]
Look into events.jl files in both `WGPUCanvas` and `WGPUgfx`. Basically `WGPUCanvas` provides hooks which `WGPUgfx` will hook into and overwrite event output. In detached mode you will all events printed out in terminal. `WGPUgfx` override events with no print statements.
