### ISSUE TITLE
Feature request: Better fetching of events

### ISSUE THREAD

**Issue by VarLad** [JuliaWGPU/WGPUgfx.jl#24]
We need a defined way to fetch the events (like mouse click, keypress etc) from the event loop.
I tried fetching the mouse state using:
```julia
		while !WindowShouldClose(scene.canvas.windowRef[])
			runApp(renderer)
			@info WGPUgfx.mouseState.leftClick
			WaitEvents()
		end
```
in the uiCircleExample.jl file.

But I'm not sure if using an unexported global variable (`mouseState`) is the best way to go about this.
I believe this needs some discussion.

**Comment by arhik** [comment]
Ideas are always welcome. You can discussion tab.

**Comment by arhik** [comment]
Since you are a member. You can use https://github.com/orgs/JuliaWGPU/projects/1. This is a feature set tracking project page.

**Comment by arhik** [comment]
@VarLad Is this done ? Or you have more ideas ? I am closing it for now.
